### PR TITLE
Fix header collision.

### LINKED ISSUE #46: error: use of undeclared identifier 'PG_TYPE_CHAR'
# Table of Contents

1.  [system info](#orgc2413f9)
2.  [reproduce with cabal and master of HDBC-postgresql](#orga782a5c)
3.  [install haskell-platform 8.6.3](#org6e5597e)
    1.  [show version](#org5901f52)
4.  [clone HDBC-postgresql](#org1720fd1)
5.  [in HDBC-postgresql install directory](#org6cc75a5)
    1.  [show git commit of hdbc-postgresql](#org6b40745)
    2.  [try to build HDBC-postgresql](#org3140389)

<a id="orgc2413f9"></a>

# system info

    system_profiler SPSoftwareDataType | grep -i System | head -n 2

    System Software Overview:
      System Version: macOS 10.14.2 (18C54)

<a id="orga782a5c"></a>

# reproduce with cabal and master of HDBC-postgresql

<a id="org6e5597e"></a>

# DONE install haskell-platform 8.6.3

<a id="org5901f52"></a>

## show version

    ghc --version

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">The Glorious Glasgow Haskell Compilation System</td>
<td class="org-left">version 8.6.3</td>
</tr>
</tbody>
</table>

<a id="org1720fd1"></a>

# DONE clone HDBC-postgresql

    git clone https://github.com/hdbc/hdbc-postgresql.git

    Cloning into 'hdbc-postgresql'...

<a id="org6cc75a5"></a>

# in HDBC-postgresql install directory

<a id="org6b40745"></a>

## show git commit of hdbc-postgresql

    git log -n1 --oneline

    f3923c3 Bump.

<a id="org3140389"></a>

## DONE try to build HDBC-postgresql

    cabal install

    Resolving dependencies...
    Configuring HDBC-postgresql-2.3.2.5...
    Building HDBC-postgresql-2.3.2.5...
    Failed to install HDBC-postgresql-2.3.2.5
    Build log ( /Users/codygman/.cabal/logs/ghc-8.6.3/HDBC-postgresql-2.3.2.5-COXC9aMUYABJ42VfzD82tr.log ):
    cabal: Entering directory '.'
    Configuring HDBC-postgresql-2.3.2.5...
    Preprocessing library for HDBC-postgresql-2.3.2.5..
    PTypeConv.hsc:53:16: error: use of undeclared identifier 'PG_TYPE_CHAR'
        hsc_const (PG_TYPE_CHAR);
                   ^
    PTypeConv.hsc:53:16: error: use of undeclared identifier 'PG_TYPE_CHAR'
    PTypeConv.hsc:53:16: error: use of undeclared identifier 'PG_TYPE_CHAR'
    PTypeConv.hsc:54:16: error: use of undeclared identifier 'PG_TYPE_CHAR2'
        hsc_const (PG_TYPE_CHAR2);
                   ^
    PTypeConv.hsc:54:16: error: use of undeclared identifier 'PG_TYPE_CHAR2'
    PTypeConv.hsc:54:16: error: use of undeclared identifier 'PG_TYPE_CHAR2'
    PTypeConv.hsc:55:16: error: use of undeclared identifier 'PG_TYPE_CHAR4'
        hsc_const (PG_TYPE_CHAR4);
                   ^
    PTypeConv.hsc:55:16: error: use of undeclared identifier 'PG_TYPE_CHAR4'
    PTypeConv.hsc:55:16: error: use of undeclared identifier 'PG_TYPE_CHAR4'
    PTypeConv.hsc:56:16: error: use of undeclared identifier 'PG_TYPE_CHAR8'
        hsc_const (PG_TYPE_CHAR8);
                   ^
    PTypeConv.hsc:56:16: error: use of undeclared identifier 'PG_TYPE_CHAR8'
    PTypeConv.hsc:56:16: error: use of undeclared identifier 'PG_TYPE_CHAR8'
    PTypeConv.hsc:57:16: error: use of undeclared identifier 'PG_TYPE_NAME'
        hsc_const (PG_TYPE_NAME);
                   ^
    PTypeConv.hsc:57:16: error: use of undeclared identifier 'PG_TYPE_NAME'
    PTypeConv.hsc:57:16: error: use of undeclared identifier 'PG_TYPE_NAME'
    PTypeConv.hsc:58:16: error: use of undeclared identifier 'PG_TYPE_BPCHAR'
        hsc_const (PG_TYPE_BPCHAR);
                   ^
    PTypeConv.hsc:58:16: error: use of undeclared identifier 'PG_TYPE_BPCHAR'
    PTypeConv.hsc:58:16: error: use of undeclared identifier 'PG_TYPE_BPCHAR'
    PTypeConv.hsc:59:16: error: use of undeclared identifier 'PG_TYPE_VARCHAR'
        hsc_const (PG_TYPE_VARCHAR);
                   ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    compiling dist/build/Database/HDBC/PostgreSQL/PTypeConv_hsc_make.c failed (exit code 1)
    command was: /usr/bin/gcc -c dist/build/Database/HDBC/PostgreSQL/PTypeConv_hsc_make.c -o dist/build/Database/HDBC/PostgreSQL/PTypeConv_hsc_make.o -fno-stack-protector -fno-stack-protector -D__GLASGOW_HASKELL__=806 -Ddarwin_BUILD_OS=1 -Dx86_64_BUILD_ARCH=1 -Ddarwin_HOST_OS=1 -Dx86_64_HOST_ARCH=1 -I/usr/local/Cellar/postgresql/11.1/include -I. -I/usr/local/Cellar/postgresql/11.1/include -Idist/build/. -DMIN_TIME_15 -Idist/build/autogen -Idist/build/global-autogen -include dist/build/autogen/cabal_macros.h -I/Library/Frameworks/GHC.framework/Versions/8.6.3-x86_64/usr/lib/ghc-8.6.3/time-1.8.0.2/include -I/Users/codygman/.cabal/lib/x86_64-osx-ghc-8.6.3/old-time-1.1.0.3-2XkcGgLYS3G4Bt8PCBG9iL/include -I/Library/Frameworks/GHC.framework/Versions/8.6.3-x86_64/usr/lib/ghc-8.6.3/bytestring-0.10.8.2/include -I/Library/Frameworks/GHC.framework/Versions/8.6.3-x86_64/usr/lib/ghc-8.6.3/base-4.12.0.0/include -I/Library/Frameworks/GHC.framework/Versions/8.6.3-x86_64/usr/lib/ghc-8.6.3/integer-gmp-1.0.2.0/include -I/Library/Frameworks/GHC.framework/Versions/8.6.3-x86_64/usr/lib/ghc-8.6.3/include -I/Library/Frameworks/GHC.framework/Versions/8.6.3-x86_64/usr/lib/ghc-8.6.3/include/
    cabal: Leaving directory '.'
    cabal: Error: some packages failed to install:
    HDBC-postgresql-2.3.2.5-COXC9aMUYABJ42VfzD82tr failed during the building
    phase. The exception was:
    ExitFailure 1

### PR DESCRIPTION
**Pull request by madf**
Starting from PostgreSQL 10.5, 9.6.10, 9.5.14, 9.4.19, 9.3.24,
and 11 Beta 3 PostgreSQL comes with its own pgtypes.h as a part of
the ecpg interface. This fix renames internal header to prevent
name collision.

Fixes #46

### CODE REVIEW

**Comment by rsoeldner** [comment]
@madf Thank you, could you please update the cabal file too, renaming `pgtypes.h`

**Comment by kosmonaffft** [comment]
Is there any chances for bugfix to be available soon in hackage?

**Comment by rsoeldner** [comment]
@kosmonaffft there was a problem with hackage permissions, I will upload it this evening

**Comment by rsoeldner** [comment]
@madf check hackage :-)

**Comment by madf** [comment]
@rsoeldner already there! Thanks for quick reaction!

**Pull request merged**
